[package]
name = "howzatt"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.6.2"
select = "*"
scraper = "*"
prettytable-rs = "*"
clap = "*"